### ISSUE TITLE
save to file/db

### ISSUE THREAD

**Issue by imSaharukh** [vladwulf/nestjs-logger-tutorial#1]
how to save these logs into a file or database?

**Comment by vladwulf** [comment]
Hi, sorry I just saw this issue.
If you need to record the logs I would use something like https://www.papertrail.com/

Additionally, if you are using a reverse proxy such as nginx you can record logs at the proxy level.
The goal of the logs in the tutorial was meant for testing/development purposes, not for recording logs for monitoring.

Also, if you are using pm2 to deploy your app you can view logs at that level as well.

Now thinking about it I realize that there are a lot of ways to achieve this result. Maybe a subject for a tutorial.
